#!/bin/sh
set -e

# Generate PHP env override file from runtime environment variables
ENV_FILE="/var/www/html/web/bin/config/env_constants.php"
mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<'PHP'
<?php
// Generated by docker-entrypoint.sh — only define when env var present
if (getenv('MDB_HOST')) define('MDB_HOST', getenv('MDB_HOST'));
if (getenv('MDB_USER')) define('MDB_USER', getenv('MDB_USER'));
if (getenv('MDB_PASSWORD')) define('MDB_PASSWORD', getenv('MDB_PASSWORD'));
if (getenv('MDB_PREFIX')) define('MDB_PREFIX', getenv('MDB_PREFIX'));
if (getenv('SOCKETIO_HOST')) define('SOCKETIO_HOST', getenv('SOCKETIO_HOST'));
if (getenv('SOCKETIO_PORT')) define('SOCKETIO_PORT', getenv('SOCKETIO_PORT'));
if (getenv('ENVIRONEMENT')) define('ENVIRONEMENT', getenv('ENVIRONEMENT'));
PHP

exec "$@"
